// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#define DellesteExpectation_cpp_check_BODY

/************************************************************
 cpp_check class body
 ************************************************************/

// include associated header file
#include "DellesteExpectation/cpp_check.h"

// Derived includes directives

// static attributes (if any)

/**
 * 
 * @return  
 */
::PrimitiveTypes::Boolean cpp_check::check() {
	return true;
}

/************************************************************
 End of cpp_check class body
 ************************************************************/
