// --------------------------------------------------------
// Code generated by Papyrus C++
// --------------------------------------------------------

#ifndef DELLESTEEXPECTATION_CPP_CHECK_H
#define DELLESTEEXPECTATION_CPP_CHECK_H

/************************************************************
 cpp_check class header
 ************************************************************/

#include "DellesteExpectation/Pkg_DellesteExpectation.h"

#include "PrimitiveTypes/Pkg_PrimitiveTypes.h"

/************************************************************/
/**
 * 
 */
class cpp_check {
public:

	/**
	 * 
	 * @return  
	 */
	::PrimitiveTypes::Boolean check();

};
/************************************************************/
/* External declarations (package visibility)               */
/************************************************************/

/* Inline functions                                         */

/************************************************************
 End of cpp_check class header
 ************************************************************/

#endif
